name: Module 4 Exercise 1 CI Pipeline

on:
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: windows-latest
    
    steps:

      - name: Install spawnctl
        shell: pwsh
        run: |
          echo "Downloading and installing spawnctl..."
          Invoke-WebRequest -Uri "https://run.spawn.cc/spawnctl.exe" -UseBasicParsing -OutFile "${{ github.workspace }}\spawnctl.exe"
          & "${{ github.workspace }}\spawnctl.exe" version
          
          & "${{ github.workspace }}\spawnctl.exe" auth
          
          & "${{ github.workspace }}\spawnctl.exe" get all
         
     
