name: Module 4 Exercise 1 CI Pipeline

on:
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: windows-latest
    
    steps:

      - name: Install spawnctl
        shell: pwsh
        run: |
          echo "Downloading and installing spawnctl..."
          Invoke-WebRequest -Uri "https://run.spawn.cc/spawnctl.exe" -UseBasicParsing -OutFile "${{ github.workspace }}\spawnctl.exe"
          Write-Host "--0----------------------------------------------------------"
          & "${{ github.workspace }}\spawnctl.exe" version
          Write-Host "--1----------------------------------------------------------"
          & "${{ github.workspace }}\spawnctl.exe" auth --debug
          Write-Host "--2----------------------------------------------------------"
          & "${{ github.workspace }}\spawnctl.exe" onboard
          Write-Host "--3----------------------------------------------------------"
          & "${{ github.workspace }}\spawnctl.exe" create access-token --purpose "dataplatform-devops-exercises/.github/workflows/token.yml"
          Write-Host "--4----------------------------------------------------------"
     
